### ISSUE TITLE
issue about a moving object

### ISSUE THREAD

**Issue by ivivyfei** [GIScience/helios#2]
hello, thank you for your great job! I am wondering if the HELIOS can simulate the moving object.  How to add a moving object and get the point cloud of this moving object?

**Comment by sebastian-bechtold** [comment]
Hello, and thank you very much for your interest in HELIOS :)

Currently, scenes with moving parts are not (easily) possible for two reasons:

- First, it's simply not implemented. However, one could derive a "MovingPartsScene" from the Scene class and add this feature.

- Second, performance is an issue: HELIOS uses raycasting to simulate the laser pulses. The raycasting algorithm is quite compute intensive, and in order to accelerate it, we perform a spatial subdivision of the scene space using a kd-tree. With the kd-tree, raycasting is fast, but building the kd-tree itself takes quite a lot of time (a very rough estimate: ~ 10 seconds for a mesh of ~ 100k triangles on an average PC). And the kd-tree needs to be rebuilt whenever the scene's geometry changes - with a moving object in the scene, this would be the case in every simulation step.

So, there are two options: You either need a new, *much* faster way to build the kd-tree (or an entirely new algorithm to simulate the trajectories of the laser pulses) - or you limit the complexity of your scene to maybe a few hundred triangles. Then, construction of the kd-tree would probably be fast enough to do it in every simulation step (without having to wait forever until the simulation is finished). Or you could even do "brute force" raycasting on the plain list of triangles, with no kd-tree at all.

What exactly do you want to simulate?

**Comment by ivivyfei** [comment]
First，thanks much to your reply. I want to build a moving target in the scene. Actually，I am doing work on autonomous rendezvous and docking using lidar.  As the target can be freely rotating, I want to simulate the approaching operation using lidar and get the point could of the target. 

Again thank you for your reply. The helios has already helped me a lot!

**Comment by sebastian-bechtold** [comment]
Hello ivivyfei!

if your entire scene consists of *one* moving/rotating object (with no additional non-moving parts), a possible solution would be to keep the scene geometry untouched and perform an *inverse* rotation/movement of the scanner/platform instead (position and orientation are relative, after all). This way you could get the same results without the prohibitive performance penalty of rebuilding the kd-tree.

Without knowing more about your scenario, it even sounds like this might be a very viable option for your use case, assuming that your docking target is floating in an otherwise empty environment and has no (relevant) individually moving sub-parts

Your project sounds very interesting, by the way. Can you tell a bit more about it? (I could also give you my e-mail address if you don't want to talk about it in public).

With best regards,

Sebastian
